<?php

namespace Database\Seeders;

use App\Models\ExamInstructionRule;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Database\Seeder;

class ExamInstructionRuleSeeder extends Seeder
{
    public function run(): void
    {
        $org = Organization::where('slug', 'demo-org')->first();
        $admin = User::where('email', 'orgadmin@examms.test')->first();

        if (! $org) {
            $this->command?->warn('ExamInstructionRuleSeeder: demo-org not found. Skipping.');

            return;
        }

        $rules = [
            [
                'rule_key' => 'no_unfair_means',
                'slug' => 'do-not-use-unfair-means-during-the-examination',
                'title' => 'Do not use unfair means during the examination.',
                'description' => 'Any form of cheating, collusion, or impersonation will lead to cancellation of the attempt.',
                'category' => 'integrity',
                'icon' => 'shield',
                'is_default' => true,
                'is_required' => true,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'no_electronic_devices',
                'slug' => 'mobile-phones-and-electronic-devices-are-prohibited',
                'title' => 'Mobile phones and electronic devices are prohibited.',
                'description' => 'Candidates must keep phones, smartwatches, and unauthorized devices away during the session.',
                'category' => 'integrity',
                'icon' => 'phone-off',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'auto_submit_on_timer',
                'slug' => 'the-exam-will-automatically-end-when-the-allotted-time-expires',
                'title' => 'The exam will automatically end when the allotted time expires.',
                'description' => 'Answers are submitted automatically when the timer reaches zero.',
                'category' => 'submission',
                'icon' => 'clock',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => ['meta' => ['honor_exam_timer' => true]],
            ],
            [
                'rule_key' => 'stable_internet',
                'slug' => 'ensure-a-stable-internet-connection',
                'title' => 'Ensure a stable internet connection.',
                'description' => 'Unstable connectivity can interrupt timing, answer sync, or final submission.',
                'category' => 'environment',
                'icon' => 'wifi',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'no_browser_close',
                'slug' => 'do-not-refresh-or-close-the-browser-window',
                'title' => 'Do not refresh or close the browser window.',
                'description' => 'Page reload or closing the window may end the attempt or lock further answers.',
                'category' => 'environment',
                'icon' => 'refresh',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'block_page_refresh' => true,
                ],
            ],
            [
                'rule_key' => 'single_login_session',
                'slug' => 'multiple-login-sessions-are-not-allowed',
                'title' => 'Multiple login sessions are not allowed.',
                'description' => 'Logging in from another device or browser may invalidate the active attempt.',
                'category' => 'integrity',
                'icon' => 'users',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'enforce_single_session' => true,
                ],
            ],
            [
                'rule_key' => 'read_questions_carefully',
                'slug' => 'read-all-questions-carefully-before-answering',
                'title' => 'Read all questions carefully before answering.',
                'description' => 'Review the full question prompt and options before recording a response.',
                'category' => 'other',
                'icon' => 'book',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'negative_marking_notice',
                'slug' => 'negative-marking-rules-apply-where-configured',
                'title' => 'Negative marking rules apply where configured.',
                'description' => 'Incorrect answers may reduce the total score according to the published marking scheme.',
                'category' => 'submission',
                'icon' => 'minus-circle',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'no_revert_after_submit',
                'slug' => 'no_revert_after_submit',
                'title' => 'Once the exam is submitted, it cannot be reverted.',
                'description' => 'Candidates cannot edit or reopen the submission after final submit.',
                'category' => 'submission',
                'icon' => 'lock',
                'is_default' => true,
                'is_required' => true,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'no_retake_after_submit',
                'slug' => 'no_retake_after_submit',
                'title' => 'Users cannot retake the exam after submission.',
                'description' => 'The same candidate cannot attempt this exam again once completed.',
                'category' => 'submission',
                'icon' => 'ban',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'tab_switch_autosubmit',
                'slug' => 'tab_switch_autosubmit',
                'title' => 'Switching tabs may auto-submit the exam.',
                'description' => 'Leaving the active exam window can immediately end the attempt.',
                'category' => 'monitoring',
                'icon' => 'tabs',
                'is_default' => true,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'detect_tab_switch' => true,
                    'focus_violation_limit' => 1,
                    'focus_violation_action' => 'auto_submit',
                    'auto_submit_on_violation' => true,
                ],
            ],
            [
                'rule_key' => 'fullscreen_required',
                'slug' => 'fullscreen_required',
                'title' => 'Full-screen mode is required during the exam.',
                'description' => 'Candidates must remain in full-screen mode for the full session.',
                'category' => 'monitoring',
                'icon' => 'maximize',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'require_fullscreen' => true,
                ],
            ],
            [
                'rule_key' => 'no_page_refresh',
                'slug' => 'no_page_refresh',
                'title' => 'Refreshing the exam page may end the attempt.',
                'description' => 'Page reload can cause automatic submission or attempt lock.',
                'category' => 'environment',
                'icon' => 'refresh',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'block_page_refresh' => true,
                ],
            ],
            [
                'rule_key' => 'disable_copy_paste',
                'slug' => 'disable_copy_paste',
                'title' => 'Disable copy/paste during the exam.',
                'description' => 'Clipboard actions can be blocked while the exam is active.',
                'category' => 'integrity',
                'icon' => 'clipboard',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'block_copy_paste' => true,
                ],
            ],
            [
                'rule_key' => 'webcam_monitoring_enabled',
                'slug' => 'webcam_monitoring_enabled',
                'title' => 'Webcam monitoring is enabled.',
                'description' => 'Candidates may be monitored by camera during the attempt.',
                'category' => 'monitoring',
                'icon' => 'camera',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'require_webcam' => true,
                ],
            ],
            [
                'rule_key' => 'microphone_required',
                'slug' => 'microphone_required',
                'title' => 'Microphone access is required before exam start.',
                'description' => 'Candidates must grant microphone access so the platform can verify an active audio input.',
                'category' => 'monitoring',
                'icon' => 'mic',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'require_microphone' => true,
                ],
            ],
            [
                'rule_key' => 'disconnection_may_affect_session',
                'slug' => 'disconnection_may_affect_session',
                'title' => 'Internet disconnection may affect the exam session.',
                'description' => 'Unstable connectivity can interrupt timing or answer sync.',
                'category' => 'environment',
                'icon' => 'wifi-off',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'single_attempt_per_question',
                'slug' => 'single_attempt_per_question',
                'title' => 'Each question can be attempted only once.',
                'description' => 'Candidates cannot return to revise an already attempted question.',
                'category' => 'submission',
                'icon' => 'one',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'single_attempt_per_question' => true,
                ],
            ],
            [
                'rule_key' => 'id_verification_required',
                'slug' => 'id_verification_required',
                'title' => 'Identity verification is required before exam start.',
                'description' => 'Candidates must capture a live selfie with the webcam before launching the test. Photo uploads are not accepted.',
                'category' => 'monitoring',
                'icon' => 'id',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'require_webcam' => true,
                    'require_photo_verification' => true,
                    'require_identity_verification' => true,
                ],
            ],
            [
                'rule_key' => 'suspicious_activity_flagged',
                'slug' => 'suspicious_activity_flagged',
                'title' => 'Suspicious activity may be flagged for review.',
                'description' => 'The platform may log unusual behavior for proctor/admin review.',
                'category' => 'monitoring',
                'icon' => 'alert',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'no_screenshots',
                'slug' => 'no_screenshots',
                'title' => 'Taking screenshots is not allowed during the exam.',
                'description' => 'Candidates must not capture screenshots or screen recordings while the exam is in progress.',
                'category' => 'integrity',
                'icon' => 'camera-off',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => false,
                'requirements' => [],
            ],
            [
                'rule_key' => 'block_devtools_and_context_menu',
                'slug' => 'block_devtools_and_context_menu',
                'title' => 'Right-click and developer tools are not allowed.',
                'description' => 'Context menu, Inspect Element, and common developer-tools shortcuts are blocked during the exam.',
                'category' => 'integrity',
                'icon' => 'ban',
                'is_default' => false,
                'is_required' => false,
                'is_actionable' => true,
                'requirements' => [
                    'block_context_menu' => true,
                    'detect_devtools' => true,
                ],
            ],
        ];

        foreach ($rules as $index => $rule) {
            ExamInstructionRule::updateOrCreate(
                [
                    'organization_id' => $org->id,
                    'rule_key' => $rule['rule_key'],
                ],
                [
                    'slug' => $rule['slug'],
                    'title' => $rule['title'],
                    'description' => $rule['description'],
                    'status' => 'active',
                    'sort_order' => ($index + 1) * 10,
                    'icon' => $rule['icon'] ?? null,
                    'category' => $rule['category'] ?? 'other',
                    'is_default' => (bool) ($rule['is_default'] ?? false),
                    'is_required' => (bool) ($rule['is_required'] ?? false),
                    'is_actionable' => (bool) ($rule['is_actionable'] ?? false),
                    'requirements' => $rule['requirements'] ?? [],
                    'created_by' => $admin?->id,
                    'updated_by' => $admin?->id,
                ]
            );
        }
    }
}
